In [7]:
import pandas as pd
import numpy  as np

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer


In [8]:
df = pd.read_csv("Reviews.csv", nrows=50000)

In [9]:
light_reviews = df[df['Text'].str.contains(r'\blight\b', case=False, na=False)]

print("Number of reviews containing 'light':", len(light_reviews))
light_reviews[['Text']].head(20)

Number of reviews containing 'light': 1415


,Text
2,This is a confection that has been around a fe...
238,A very delicate green tea with a smooth light ...
269,This is a delicious sugar. It has a pretty lig...
396,Arrowhead Mills Buttermilk Pancake mix is my f...
404,A good tasting light chip that has some value ...
462,Kettle Chips flavors can be hit or miss. Some...
466,"I'm addicted to salty and tangy flavors, so wh..."
467,These Honey Dijon chips bring a terrific balan...
486,Just got this order and it is ok. A bit light ...
556,DEfintely not as tasty as the Madhouse Munchie...


In [10]:
sentences = [
    "This olive oil is wonderful and very light on the stomach.",
    "The packaging was broken and let too much light inside the box.",
    "I prefer this brand because it is a light and healthy snack."
]

In [11]:

vectorizer = CountVectorizer()

dtm = vectorizer.fit_transform(sentences)

In [12]:
dense_matrix = dtm.toarray()

print(dense_matrix)

[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]


In [13]:
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

print("vec_1 =", vec_1)
print("vec_2 =", vec_2)
print("vec_3 =", vec_3)

vec_1 = [1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
vec_2 = [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
vec_3 = [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


In [14]:


similarity_1_2 = cosine_similarity(
    [vec_1],
    [vec_2]
)

print("Similarity between Sentence 1 and Sentence 2:")
print(similarity_1_2[0][0])

Similarity between Sentence 1 and Sentence 2:
0.3223291856101521


In [15]:
# Dot Product Similarities
similarity_1_2 = np.dot(vec_1, vec_2)
similarity_1_3 = np.dot(vec_1, vec_3)

# Console Output
print("Similarity between Sentence 1 and Sentence 2 (Different Contexts):")
print(similarity_1_2)

print("\nSimilarity between Sentence 1 and Sentence 3 (Similar Contexts):")
print(similarity_1_3)

Similarity between Sentence 1 and Sentence 2 (Different Contexts):
4

Similarity between Sentence 1 and Sentence 3 (Similar Contexts):
4
